### PR TITLE
Use C++11's unique_ptr instead of auto_ptr

### PR DESCRIPTION
**Pull request by jhasse**
Removes deprecation warnings with newer compilers.

### CODE REVIEW

**Comment by jhasse** [comment]
Ups, this is basically the same as #77, I overlooked it.

Btw: Would you be okay with moving this repository into the wxFormBuilder organization?

**Comment by jhasse** [comment]
Okay build server was failing because of missing `-std=c++14` flag, now fixed :)

**Comment by rjpcomputing** [comment]
@jhasse 

I moved the repo to wxFormBuilder

**Comment by jhasse** [comment]
Awesome, thank you! :)

**Pull request merged**
